### ISSUE TITLE
How do you get the 'bottleneck_weights.h5' file?

### ISSUE THREAD

**Issue by jfantell** [rdcolema/keras-image-classification#4]
Hi,

I am brand new to keras and machine learning in general. I want to create a keras model using the 'cats_n_dogs.ipynb' file, but I am not sure where to find the required 'bottleneck_weights.h5' file. Is there a link I can download the file from? I have already downloaded the 'vgg16_weights.h5' file.

**Comment by rdcolema** [comment]
Hi, 

The `bottleneck_weights.h5` file is actually created and saved by the `train_bottleneck_model` function, so it's not something you need to have beforehand. 

Let me know if that helps,
-RC
