### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vani99** [rdcolema/keras-image-classification#6]
I'm actually using AWS sagemaker as the platform and have the dadaset both in my local system and as well as in s3 bucket. But receiving the same error for both datasets! Receiving this the following error while trying to run the following code:

train_data, train_target, train_id = normalize_train_data()

Loading training images...
Loading dogs files (Index: 0)
Loading cats files (Index: 1)
Training data load time: 0.0 seconds
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-c1ffe3d32c28> in <module>()
----> 1 train_data, train_target, train_id = normalize_train_data()

<ipython-input-26-03aa22a511d6> in normalize_train_data()
      5     train_target = np.array(train_target, dtype=np.uint8)
      6 
----> 7     train_data = train_data.transpose((0, 3, 1, 2))
      8 
      9     train_data = train_data.astype('float32')

ValueError: axes don't match array

**Comment by rdcolema** [comment]
Hey @vani99 are you sure the images are being loaded? What shape is the array before it gets to the transpose line?

See https://github.com/ZFTurbo/KAGGLE_DISTRACTED_DRIVER/issues/4 for a similar issue.
